version: "3.9"

services:
  vpd_app:
    build: .
    container_name: vpd_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./vpd_historico.json:/app/vpd_historico.json
    restart: unless-stopped
