[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#00FF00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false